server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: springboot-week03 测试环境

app:
  app-name: 企业后台管理系统
  version: 2.0.0
  description: 基于 Spring Boot 3.5.11 构建
  published: false
  author:
    name: wjz
    email: 2165290792@qq.com
  features:
    - "基于 Spring Boot 3.5.11 构建"
    - "集成 Spring Security"
    - "集成 Spring Data Redis"